

export const instrumentosLista = [
  'Acordeão', 'Banjo', 'Baixo Eléctrico', 'Bombo', 'Bombardino', 'Caixa',
  'Cavaquinho', 'Clarinete', 'Contrabaixo', 'Fagote', 'Flauta',
  'Guitarra Clássica', 'Guitarra Eléctrica', 'Harmónica', 'Maestro',
  'Marimba', 'Oboé', 'Órgão', 'Outro', 'Piano', 'Pratos', 'Saxofone Alto',
  'Saxofone Barítono', 'Saxofone Tenor', 'Sintetizador', 'Tímpanos',
  'Trombone', 'Trompa', 'Trompete', 'Tuba', 'Ukulele', 'Violino',
  'Violoncelo', 'Viola', 'Voz', 'Xilofone'
];

export const iconesInstrumentos: Record<string, { name: string; color?: string }> = {
  Acordeão: { name: 'piano', color: '#c92a2a' },
  Banjo: { name: 'guitar-acoustic', color: '#ae3ec9' },
  'Baixo Eléctrico': { name: 'guitar-electric', color: '#d9480f' },
  Bombo: { name: 'disc', color: '#e64980' },
  Bombardino: { name: 'bugle', color: '#fab005' },
  Caixa: { name: 'midi-port', color: '#d6336c' },
  Cavaquinho: { name: 'guitar-acoustic', color: '#ae3ec9' },
  Clarinete: { name: 'music-note', color: '#12b886' },
  Contrabaixo: { name: 'violin', color: '#4263eb' },
  Fagote: { name: 'music-note', color: '#0b7285' },
  Flauta: { name: 'music', color: '#0ca678' },
  'Guitarra Clássica': { name: 'guitar-acoustic', color: '#e67700' },
  'Guitarra Eléctrica': { name: 'guitar-electric', color: '#e8590c' },
  Harmónica: { name: 'music-note', color: '#c2255c' },
  Maestro: { name: 'account-tie', color: '#495057' },
  Marimba: { name: 'music-note', color: '#e64980' },
  Oboé: { name: 'music-note', color: '#20c997' },
  Órgão: { name: 'piano', color: '#364fc7' },
  Outro: { name: 'help-circle-outline', color: '#868e96' },
  Piano: { name: 'piano', color: '#7950f2' },
  Pratos: { name: 'disc', color: '#f06595' },
  Saxofone: { name: 'saxophone', color: '#339af0' },
  'Saxofone Alto': { name: 'saxophone', color: '#339af0' },
  'Saxofone Tenor': { name: 'saxophone', color: '#339af0' },
  'Saxofone Barítono': { name: 'saxophone', color: '#339af0' },
  Sintetizador: { name: 'piano', color: '#3b5bdb' },
  Tímpanos: { name: 'album', color: '#e64980' },
  Trombone: { name: 'bugle', color: '#fab005' },
  Trompa: { name: 'bugle', color: '#fcc419' },
  Trompete: { name: 'trumpet', color: '#fab005' },
  Tuba: { name: 'bullhorn-variant', color: '#fab005' },
  Ukulele: { name: 'guitar-acoustic', color: '#be4bdb' },
  Viola: { name: 'violin', color: '#5f3dc4' },
  Violino: { name: 'violin', color: '#6741d9' },
  Violoncelo: { name: 'violin', color: '#4c6ef5' },
  Voz: { name: 'microphone', color: '#e64980' },
  Xilofone: { name: 'piano', color: '#e64980' },
};
